# cloudbuild.yaml
timeout: 1200s          # 20 min max build time
substitutions:
  _REGION: europe-west1
  _SERVICE: fastapi-demo

steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','$_REGION-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi:$SHORT_SHA','.']

# 2. Push it to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','$_REGION-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi:$SHORT_SHA']

# 3. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE'
  - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi:$SHORT_SHA'
  - '--region=$_REGION'
  - '--service-account=fastapi-runtime@$PROJECT_ID.iam.gserviceaccount.com'
  - '--no-allow-unauthenticated'
  - '--quiet'

images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi:$SHORT_SHA'