name: Sheet-to-Doc-LLM

on:
  repository_dispatch:
    types: [sheet-llm-request]   # <-- must match event_type sent by Apps Script

jobs:
  run:
    runs-on: ubuntu-latest
    env:
    #   # Pull values straight out of the dispatch payload
      SHEET_ID: ${{ github.event.client_payload.sheet_id }}
    #   LLM_PROMPT: ${{ github.event.client_payload.prompt }}
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcreds.json
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Write Google service account key
      run: echo '${{ secrets.GOOGLE_CREDS_JSON }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pipeline
      run: python -m app.sheets